all:
    code: "Tu codigo pin es {pin}"
    free: "Abre el siguiente enlace para seguir jugando. http://juganar.com/main/playwin"
    pin:  "Tu pin es {pin} y ahora puedes jugar http://juganar.com/playwin

