all:
    authorized_users:
        lloyd: thesame
        lionel: jefe
        jason: london
    secure_methods:
        admin: 
        game:
dev:
    authorized_users:
        user: pass 
    secure_methods:
        admin: 
        game:
