correlationId    : 0 
consumerId       : 0 
referenceId      : 0 
tariffClass      : dunno 
serviceName      : dunno 
serviceCategory  : dunno 
serviceMetaData  : dunno 
eventCount       : 3  
duration         : 0 
frequencyInterval: 100 
frequencyCount   : 3 
VAT              : 0.0 
campaignName     : adsalsasms 
username         : one-nl 
password         : R1bh5q6VYL
clientIPAddress  : 111.222.333.444 
returnURL        : our.url.com 
